# Dependency Review Action
#
# This Action will scan dependency manifest files that change as part of a Pull Request, surfacing known-vulnerable versions of the packages declared or updated in the PR. Once installed, if the workflow run is marked as required, PRs introducing known-vulnerable packages will be blocked from merging.
#
# Source repository: https://github.com/actions/dependency-review-action
# Public documentation: https://docs.github.com/en/code-security/supply-chain-security/understanding-your-software-supply-chain/about-dependency-review#dependency-review-enforcement
name: 'Dependency Review'
on: [pull_request]

permissions:
  contents: read

jobs:
  dependency-review:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout Repository'
        uses: actions/checkout@v3
      - name: 'Dependency Review'
        uses: actions/dependency-review-action@v3
      - name: Python Unit Test
      # You may pin to the exact commit or the version.
      # uses: onichandame/python-test-action@6a1d618300de7ea0b753e50819e093a7e5a5f60b
        uses: onichandame/python-test-action@0.0.0
        # with:
          # dependency list
          # deps_list: # default is requirements.txt
          # # path of git repo relative to GITHUB_WORKSPACE(no trailing slash)
          # path: # default is 
          # # directory of test scripts
          # test_dir: # default is .
          # # pattern of the test script name
          # pattern: # default is test_*.py
          
